version: "3.9"

services:
  db:
    image: postgres:15
    container_name: bakes_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bakes_on_demand_production
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: bakes_app
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:password@db:5432/bakes_on_demand_production
      RAILS_MASTER_KEY: 1d279db56aec9b4dc82584612024d9e4
    ports:
      - "3000:3000"
    command: bash -c "bundle exec rails db:prepare && bundle exec rails server -b 0.0.0.0 -p 3000"

volumes:
  postgres_data:
