
default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: bakes_on_demand_development
  username: postgres
  password: postgres
  host:     localhost


test:
  <<: *default
  database: bakes_on_demand_test
  username: postgres
  password: postgres
  host:     localhost

production:
  url: <%= ENV['DATABASE_URL'] %>
